### ISSUE TITLE
Metadata.csv questions

### ISSUE THREAD

**Issue by CHK-0000** [CODEJIN/NaturalSpeech2#9]
(s) c:\NaturalSpeech2>python C:\NaturalSpeech2\Pattern_Generator.py -lj C:\NaturalSpeech2\dataset\train -hp C:\NaturalSpeech2\Hyper_Parameters.yaml
C:\Users\user\.conda\envs\s\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "C:\NaturalSpeech2\Pattern_Generator.py", line 1443, in <module>
    lj_paths, lj_text_dict, lj_pronunciation_dict, lj_speaker_dict, lj_emotion_dict, lj_language_dict, lj_gender_dict = LJ_Info_Load(path= args.lj_path)
  File "C:\NaturalSpeech2\Pattern_Generator.py", line 1042, in LJ_Info_Load
    for line in open(os.path.join(path, 'metadata.csv').replace('\\', '/'), 'r', encoding= 'utf-8-sig').readlines():
FileNotFoundError: [Errno 2] No such file or directory: 'C:/NaturalSpeech2/dataset/train/metadata.csv'
___
I'm getting the above error, where can I get the metadata.csv? Please let me know the format of the data. Thanks.

**Comment by CODEJIN** [comment]
Dear @ksl103177 ,

Hello. Is the 'C:\NaturalSpeech2\dataset' you specified where the LJSpeech dataset is located?
metadata.csv is located at the root of the dataset. To be exact, the unzipped LJSpeech dataset consists of one folder and two files as follows.

-wavs
-metadata.csv
-README

If there is no metadata.csv in your LJSpeech dataset, download it again from [here](https://keithito.com/LJ-Speech-Dataset/) and unzip it.

Best regards.

**Comment by CHK-0000** [comment]
Oh, thank you, I have another question.
In the Hyper_Parameters.yaml file, should I use the Path: 'C:\NaturalSpeech2\LJSpeech-1.1\wavs' path in Train_pattern as the train data and the data in Eval_Pattern should be in the same format?

**Comment by CODEJIN** [comment]
No. The train and eval paths are the locations where the training data is generated. Pattern_Generator.py outputs a completely separate pickled file from the dataset and inputs it into the specified folder. Therefore, the train and eval paths should not be LJSpeech-1.1 but rather a new folder should be designated.
